name: "screeps-client"

services:
  client:
    build: .
    volumes:
      - ${SCREEPS_NW_PATH:?"SCREEPS_NW_PATH not set"}:/screeps.nw
    command:
      - "start"
      - "--"
      - "--package=/screeps.nw"
      - "--host=0.0.0.0"
    ports:
      - "${SCREEPS_PROXY_HOST:-127.0.0.1}:8080:8080/tcp"
    restart: unless-stopped
